version: '3'


services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: TiendaOnion
    ports:
      - 80:80
    networks:   
      - onion-app
networks:      
  onion-app:
    external: true
      
